name: vaevae_concat_1
seed: 0

experiment: Fusion_MVAE_Experiment

max_epochs: 30
min_epochs: 30

latent_dim: 20
objective: vaevae_elbo

datamodule: MNIST_SVHN_DataModule
datamodule_args:
  data_dir: data
  batch_size: 256
  val_split: 50_000

prior: standard_normal
prior_args: {}

approx_posterior: diagonal_normal
approx_posterior_args: {}

encoder: [MNISTEncoder2, SVHNEncoder]
encoder_args: [{}, {}]

fusion_module: ConcatEncoder
fusion_module_args: {}

likelihood: [ConditionalIndependentBernoulli, ConditionalIndependentBernoulli]
likelihood_args: [{}, {}]

decoder: [MNISTDecoder2, SVHNDecoder]
decoder_args: [{}, {}]

optimizer: Adam
# To tune
learning_rate: 0.0003
optimizer_args: {}

# To tune
kl_warmup_fraction: 0.3
kl_multiplier_initial: 1
kl_multiplier_max: 1

earlystop_patience: 5
