name: vaevae_postflow_svhn_1
seed: 0

experiment: PoE_MVAE_Experiment

max_epochs: 10

latent_dim: 20
objective: vaevae_elbo

datamodule: MNIST_SVHN_DataModule
datamodule_args:
  data_dir: data
  batch_size: 256
  val_split: 50_000
  # num_workers: 0

prior: standard_normal
prior_args: {}

approx_posterior: flow
approx_posterior_args:
  n_flow_steps: 5

encoder: [MNISTEncoder1, SVHNEncoder]
encoder_args: [{}, {}]

likelihood: [ConditionalIndependentBernoulli, ConditionalIndependentBernoulli]
likelihood_args: [{}, {}]

decoder: [MNISTDecoder1, SVHNDecoder]
decoder_args: [{}, {}]

optimizer: Adam
optimizer_args:
  lr: 0.001

# To tune
kl_warmup_fraction: 0.3
kl_multiplier_initial: 0
kl_multiplier_max: 1

earlystop_patience: 5
