name: allvae_0
seed: 0

experiment: PoE_MVAE_Experiment

max_epochs: 50

latent_dim: 20
objective: all_elbo

datamodule: datamodules.MNIST_SVHN_DataModule
datamodule_args:
  data_dir: data
  batch_size: 256
  val_split: 50_000

prior: models.standard_normal
prior_args:

approx_posterior: models.diagonal_normal
approx_posterior_args:

encoder:
  - models.MNISTEncoder1
  - models.SVHNEncoder
encoder_args:

likelihood:
  - models.ConditionalIndependentBernoulli
  - models.ConditionalIndependentBernoulli
likelihood_args:

decoder:
  - models.MNISTDecoder1
  - models.SVHNDecoder
decoder_args:

optimizer: optim.Adam
optimizer_args:
  lr: 0.0003

gradient_clip_val: 0.0

# To tune
kl_warmup_fraction: 0.3
kl_multiplier_initial: 1
kl_multiplier_max: 1

earlystop_patience: 5
