name: mvae_test
seed: 0

experiment: MultimodalVAEExperiment

max_steps: 150_000

latent_dim: 40
objective: mvae_elbo

datamodule: MultimodalMNISTDataModule
datamodule_args:
  data_dir: data
  batch_size: 256
  # num_workers: 0

prior: standard_normal
prior_args: {}

approx_posterior: diagonal_normal
approx_posterior_args: {}

encoder: [MNISTEncoder1, LabelEncoder]
encoder_args: [{}, {}]

inputs_encoder: ProductOfExpertsEncoder
inputs_encoder_args: {}

likelihood: [ConditionalIndependentBernoulli, ConditionalCategorical]
likelihood_args: [{}, {}]

decoder: [MNISTDecoder1, LabelDecoder]
decoder_args: [{}, {}]

optimizer: Adam
optimizer_args:
  lr: 0.0005

kl_warmup_fraction: 0.1
kl_multiplier_initial: 0.5
kl_multiplier_max: 1
