name: elbo
seed: 0

experiment: VAEExperiment

max_epochs: 100

z_dim: 20

datamodule: MNISTDataModule
datamodule_args:
  data_dir: data

encoder: MNISTEncoder
encoder_args:

decoder: MNISTDecoder
decoder_args:

vae: VAE
vae_args:

loss: elbo_loss_mc
loss_args:
  # K: 10

optimizer: Adam
optimizer_args:
  lr: 0.001
