name: langevin
seed: 0

experiment: VAELangevinExperiment

max_epochs: 100

z_dim: 20

datamodule: MNISTDataModule
datamodule_args:
  data_dir: data

encoder: MNISTLangevinEncoder
encoder_args:
  eps: 0.01
  s: 5
  t: 5

decoder: MNISTDecoder
decoder_args:

vae: VAE
vae_args:

loss: elbo_loss_mc
loss_args:
  # K: 10

optimizer: Adam
optimizer_args:
  lr: 0.001
