name: elbo_flow
seed: 0

experiment: VAEFlowExperiment

# max_epochs: 100
max_steps: 150_000

z_dim: 20

datamodule: MNISTDataModule
datamodule_args:
  data_dir: data

flow: PlanarModel
flow_args:
  n_layers: 10

encoder: MNISTFlowEncoder
encoder_args:

decoder: MNISTDecoder
decoder_args:

vae: VAE
vae_args:

loss: elbo_loss_mc
loss_args:
  # K: 10

optimizer: Adam
optimizer_args:
  lr: 0.001
